# Generated by Django 5.2.3 on 2025-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pg',
            old_name='rent',
            new_name='area_sqft',
        ),
        migrations.RenameField(
            model_name='pg',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='pg',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='image',
        ),
        migrations.AddField(
            model_name='pg',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='available_for',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='bathroom_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='bed_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='bhk_type',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='booking_type',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='facilities',
            field=models.TextField(default='Basic Facilities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='furnishing_type',
            field=models.CharField(default='Semi-Furnished', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='house_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pg',
            name='min_rent',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='min_room_advance',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='min_room_rent',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='room_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pg',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
