# Generated by Django 5.2.3 on 2025-06-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_rent_pg_area_sqft_rename_name_pg_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.AddField(
            model_name='tenant',
            name='joined_on',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.pg'),
        ),
    ]
