# Generated by Django 5.2.3 on 2025-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_tenant_email_remove_tenant_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
