# Generated by Django 5.2.3 on 2025-08-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('date_raised', models.DateField(auto_now_add=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tenant')),
            ],
        ),
    ]
