# Generated by Django 5.2.3 on 2025-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
