# Generated by Django 5.2.3 on 2025-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='pg_images/'),
        ),
    ]
